# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=aarch64 -mcpu=apple-m1 -run-pass=early-ifcvt -o - %s | FileCheck %s


--- |
  define i32 @cascade_selector(ptr %p) {
    ret i32 0
  }
  define i32 @cascade_with_copy_from_load(ptr %p) {
    ret i32 0
  }
...
---
name:            cascade_selector
alignment:       4
tracksRegLiveness: true
liveins:
  - { reg: '$x0', virtual-reg: '%0' }
body:             |
  ; CHECK-LABEL: name: cascade_selector
  ; CHECK: bb.0:
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
  ; CHECK-NEXT:   [[LDRWui:%[0-9]+]]:gpr32common = LDRWui [[COPY]], 0 :: (load (s32))
  ; CHECK-NEXT:   [[MOVi32imm:%[0-9]+]]:gpr32 = MOVi32imm 42
  ; CHECK-NEXT:   [[MOVi32imm1:%[0-9]+]]:gpr32 = MOVi32imm 43
  ; CHECK-NEXT:   [[MOVi32imm2:%[0-9]+]]:gpr32 = MOVi32imm 44
  ; CHECK-NEXT:   [[MOVi32imm3:%[0-9]+]]:gpr32 = MOVi32imm 45
  ; CHECK-NEXT:   [[SUBSWri:%[0-9]+]]:gpr32 = SUBSWri [[LDRWui]], 5, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSINCWr:%[0-9]+]]:gpr32 = CSINCWr $wzr, $wzr, 13, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri1:%[0-9]+]]:gpr32 = SUBSWri [[LDRWui]], 4, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm3]], [[CSINCWr]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri2:%[0-9]+]]:gpr32 = SUBSWri [[LDRWui]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr1:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm2]], [[CSELWr]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri3:%[0-9]+]]:gpr32 = SUBSWri [[LDRWui]], 2, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr2:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm1]], [[CSELWr1]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri4:%[0-9]+]]:gpr32 = SUBSWri [[LDRWui]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr3:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm]], [[CSELWr2]], 12, implicit $nzcv
  ; CHECK-NEXT:   $w0 = COPY [[CSELWr3]]
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  bb.0:
    successors: %bb.5(0x40000000), %bb.1(0x40000000)
    liveins: $x0

    %0:gpr64sp = COPY $x0
    %38:gpr32common = LDRWui %0, 0 :: (load (s32))
    %40:gpr32 = MOVi32imm 42
    %41:gpr32 = SUBSWri %38, 1, 0, implicit-def $nzcv
    Bcc 12, %bb.5, implicit $nzcv
    B %bb.1

  bb.1:
    successors: %bb.5(0x40000000), %bb.2(0x40000000)

    %42:gpr32 = MOVi32imm 43
    %43:gpr32 = SUBSWri %38, 2, 0, implicit-def $nzcv
    Bcc 12, %bb.5, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.5(0x40000000), %bb.3(0x40000000)

    %44:gpr32 = MOVi32imm 44
    %45:gpr32 = SUBSWri %38, 3, 0, implicit-def $nzcv
    Bcc 12, %bb.5, implicit $nzcv
    B %bb.3

  bb.3:
    successors: %bb.5(0x40000000), %bb.4(0x40000000)

    %46:gpr32 = MOVi32imm 45
    %47:gpr32 = SUBSWri %38, 4, 0, implicit-def $nzcv
    Bcc 12, %bb.5, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.5(0x80000000)

    %48:gpr32 = SUBSWri %38, 5, 0, implicit-def $nzcv
    %49:gpr32 = CSINCWr $wzr, $wzr, 13, implicit $nzcv

  bb.5:
    %100:gpr32 = PHI %40, %bb.0, %42, %bb.1, %44, %bb.2, %46, %bb.3, %49, %bb.4
    $w0 = COPY %100
    RET_ReallyLR implicit $w0
...
---
name:            cascade_with_copy_from_load
alignment:       4
tracksRegLiveness: true
liveins:
  - { reg: '$x0', virtual-reg: '%0' }
body:             |
  ; CHECK-LABEL: name: cascade_with_copy_from_load
  ; CHECK: bb.0:
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
  ; CHECK-NEXT:   [[LDRWui:%[0-9]+]]:gpr32common = LDRWui [[COPY]], 0 :: (load (s32))
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32common = COPY [[LDRWui]]
  ; CHECK-NEXT:   [[MOVi32imm:%[0-9]+]]:gpr32 = MOVi32imm 7
  ; CHECK-NEXT:   [[MOVi32imm1:%[0-9]+]]:gpr32 = MOVi32imm 6
  ; CHECK-NEXT:   [[MOVi32imm2:%[0-9]+]]:gpr32 = MOVi32imm 5
  ; CHECK-NEXT:   [[MOVi32imm3:%[0-9]+]]:gpr32 = MOVi32imm 4
  ; CHECK-NEXT:   [[MOVi32imm4:%[0-9]+]]:gpr32 = MOVi32imm 3
  ; CHECK-NEXT:   [[MOVi32imm5:%[0-9]+]]:gpr32 = MOVi32imm 2
  ; CHECK-NEXT:   [[SUBSWri:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 7, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSINCWr:%[0-9]+]]:gpr32 = CSINCWr $wzr, $wzr, 13, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri1:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 6, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm5]], [[CSINCWr]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri2:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 5, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr1:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm4]], [[CSELWr]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri3:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 4, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr2:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm3]], [[CSELWr1]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri4:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr3:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm2]], [[CSELWr2]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri5:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 2, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr4:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm1]], [[CSELWr3]], 12, implicit $nzcv
  ; CHECK-NEXT:   [[SUBSWri6:%[0-9]+]]:gpr32 = SUBSWri [[COPY1]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[CSELWr5:%[0-9]+]]:gpr32 = CSELWr [[MOVi32imm]], [[CSELWr4]], 12, implicit $nzcv
  ; CHECK-NEXT:   $w0 = COPY [[CSELWr5]]
  ; CHECK-NEXT:   RET_ReallyLR implicit $w0
  bb.0:
    successors: %bb.7(0x40000000), %bb.1(0x40000000)
    liveins: $x0

    %0:gpr64sp = COPY $x0
    %10:gpr32common = LDRWui %0, 0 :: (load (s32))
    %38:gpr32common = COPY %10
    %40:gpr32 = MOVi32imm 7
    %41:gpr32 = SUBSWri %38, 1, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.1

  bb.1:
    successors: %bb.7(0x40000000), %bb.2(0x40000000)

    %42:gpr32 = MOVi32imm 6
    %43:gpr32 = SUBSWri %38, 2, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.2

  bb.2:
    successors: %bb.7(0x40000000), %bb.3(0x40000000)

    %44:gpr32 = MOVi32imm 5
    %45:gpr32 = SUBSWri %38, 3, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.3

  bb.3:
    successors: %bb.7(0x40000000), %bb.4(0x40000000)

    %46:gpr32 = MOVi32imm 4
    %47:gpr32 = SUBSWri %38, 4, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.4

  bb.4:
    successors: %bb.7(0x40000000), %bb.5(0x40000000)

    %48:gpr32 = MOVi32imm 3
    %49:gpr32 = SUBSWri %38, 5, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.5

  bb.5:
    successors: %bb.7(0x40000000), %bb.6(0x40000000)

    %50:gpr32 = MOVi32imm 2
    %51:gpr32 = SUBSWri %38, 6, 0, implicit-def $nzcv
    Bcc 12, %bb.7, implicit $nzcv
    B %bb.6

  bb.6:
    successors: %bb.7(0x80000000)

    %52:gpr32 = SUBSWri %38, 7, 0, implicit-def $nzcv
    %53:gpr32 = CSINCWr $wzr, $wzr, 13, implicit $nzcv

  bb.7:
    %100:gpr32 = PHI %40, %bb.0, %42, %bb.1, %44, %bb.2, %46, %bb.3, %48, %bb.4, %50, %bb.5, %53, %bb.6
    $w0 = COPY %100
    RET_ReallyLR implicit $w0
...
